name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build prompt index
      run: |
        python scripts/build_index.py
        git diff --exit-code prompts/INDEX.md
    - name: Test example (placeholder)
      run: echo "Add your tests here"
